# Generated by Django 3.2.15 on 2023-12-16 09:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_auto_20231215_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientinrecipe',
            name='amount',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1, message='Не менее 1 единицы'), django.core.validators.MaxValueValidator(1000, message='Не менее 1 единицы')], verbose_name='Количество'),
        ),
    ]
