# Generated by Django 3.2.15 on 2023-12-17 21:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_alter_ingredientinrecipe_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientinrecipe',
            name='amount',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1, message='Не менее 1 единицы'), django.core.validators.MaxValueValidator(1000, message='Не более 1000')], verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1, message='Не менее 1 единицы'), django.core.validators.MaxValueValidator(32000, message='Не более 32 000 минут!')], verbose_name='Время приготовления блюда'),
        ),
    ]
