# Generated by Django 3.2.15 on 2023-12-06 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscribe',
            options={'ordering': ['id'], 'verbose_name': 'Подписка', 'verbose_name_plural': 'Подписки'},
        ),
        migrations.AlterField(
            model_name='projectuser',
            name='email',
            field=models.EmailField(error_messages={'unique': 'Пользователь с таким email уже зарегистрирован'}, max_length=254, unique=True, verbose_name='Твоя электронная почта'),
        ),
        migrations.AlterField(
            model_name='projectuser',
            name='first_name',
            field=models.CharField(max_length=150, verbose_name='Твое имя'),
        ),
        migrations.AlterField(
            model_name='projectuser',
            name='last_name',
            field=models.CharField(max_length=150, verbose_name='Твоя фамилия'),
        ),
        migrations.AlterField(
            model_name='projectuser',
            name='username',
            field=models.CharField(error_messages={'unique': 'Пользователь с таким никнэймом уже зарегистрирован'}, max_length=150, unique=True, verbose_name='Твой никнэйм'),
        ),
    ]
