# Generated by Django 3.2.15 on 2023-12-14 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20231206_1419'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectuser',
            options={'ordering': ('username',), 'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterModelOptions(
            name='subscribe',
            options={'ordering': ['author_id'], 'verbose_name': 'Подписка', 'verbose_name_plural': 'Подписки'},
        ),
    ]
